CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		project2_Bentz_mlb0119.o

LIBS =

TARGET =	project2_Bentz_mlb0119.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
